name: catscan
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  archive: ^3.3.7
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_downloader: ^1.7.0
  flutter_file_downloader: ^1.1.2
  flutter_image_compress: ^2.0.4
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.1
  json_serializable: ^6.7.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  share_plus: ^7.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
